[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  publish = "build" # build 폴더 경로 (React 앱의 경우)
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
